Reverting changes in v.1 2 because of issues:
Exception in thread Thread-9:
Traceback (most recent call last):
  File "threading.py", line 442, in __bootstrap
    self.run()
  File "/home/siebrand/pywikipedia/threadpool.py", line 106, in run
    self.pool.jobLock.release()
error: release unlocked lock


git-svn-id: http://svn.wikimedia.org/svnroot/pywikipedia/trunk/pywikipedia@3593 6a7f98fc-eeb0-4dc1-a6e2-c2c589a08aa6